# Generated by Django 3.0.7 on 2020-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200607_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('dimention', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('hall', models.CharField(max_length=3)),
                ('balcany', models.CharField(max_length=3)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('user_email', models.CharField(max_length=100)),
                ('dimention', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('kitchen', models.CharField(max_length=3)),
            ],
        ),
    ]
