# Generated by Django 3.0.7 on 2020-06-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_house_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='dimention',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='floors',
            new_name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='house',
            name='AC',
            field=models.CharField(default='no', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='lko', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='house',
            name='img',
            field=models.ImageField(default='img', upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='state',
            field=models.CharField(default='up', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='AC',
            field=models.CharField(default='no', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='balcany',
            field=models.CharField(default='y', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.CharField(default='lko', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='comment',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='hall',
            field=models.CharField(default='y', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(default='1', upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.CharField(default='up', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='lko', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='up', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='kitchen',
            field=models.IntegerField(),
        ),
    ]
