# Generated by Django 3.0.7 on 2020-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200612_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='kitchen',
            field=models.CharField(max_length=3),
        ),
    ]
