# Generated by Django 3.0.7 on 2020-06-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200612_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='comment',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='comment',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
