# Generated by Django 3.0.7 on 2020-06-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200612_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='Area',
            new_name='area',
        ),
    ]
